name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Cache Gems
        uses: actions/cache@v4
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'
          bundler-cache: true

      - name: Install Bundler
        run: |
          gem install bundler

      - name: Install dependencies
        run: |
          bundle install --path vendor/bundle

      - name: Check JSON Syntax
        uses: limitusus/json-syntax-check@v1
        with:
          pattern: "\\bio.json$"

      - name: Build and Deploy with Jekyll Action
        uses: helaili/jekyll-action@2.5.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target_branch: 'gh-pages'
